
import {
  GraphQLInt,
  GraphQLList,
  GraphQLNonNull,
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString,
  GraphQLFloat
} from 'graphql'

import {cellPointType, fetchCellDataDetails} from './types/cellPoint'
import {BBKNNType, fetchBBKNNDetails} from './types/bbknn'
import {HarmonyType, fetchHarmonyDetails} from './types/harmony'
import {RNAType, fetchRNADetails} from './types/rna'
import {ScanoramaType, fetchScanoramaDetails} from './types/scanorama'
import {MetadataType, fetchMetadataDetails} from './types/metadata'
//import {ExpressionType, fetchExpressionDetails} from './types/expression'
import {CellTypeType, fetchCellTypeDetails} from './types/cellType'


import {umapType, fetchUmapData} from './types/umap'
import {expressionType, fetchExpressionData} from './types/expression'

console.log('hello')

const rootType = new GraphQLObjectType({
  name: 'Root',
  description: `
The fields below allow for different ways to look up RC2 data.
  `,
  fields: () => ({

    umap : {
      description: 'Retrieve UMAP data',
      type: new GraphQLList(umapType),

      args: {
        dataset: { type: GraphQLString },
      },
      resolve: (obj, args, ctx) => {
        return fetchUmapData(ctx,args.dataset)
      },
    },

    expression : {
      description: 'Retrieve gene expression data',
      type: new GraphQLList(expressionType),

      args: {
        gene: { type: GraphQLString },
      },
      resolve: (obj, args, ctx) => {
        return fetchExpressionData(ctx,args.gene)
      },
    },



    cell_point : {
      description: 'Look up Cell Data',
      type: new GraphQLList(cellPointType),

      args: {
        cell_id: { type: GraphQLInt },
        x_value: { type: GraphQLFloat },
        y_value: { type: GraphQLFloat },
        cluster: { type: GraphQLString }
      },
      resolve: (obj, args, ctx) => {
        return fetchCellDataDetails(ctx)
      },
    },    
    bbknn_point : {
      description: 'Look up BBKNN Data',
      type: new GraphQLList(BBKNNType),

      args: {
        cell_id: { type: GraphQLString },
        x_value: { type: GraphQLFloat },
        y_value: { type: GraphQLFloat },
      },
      resolve: (obj, args, ctx) => {
        return fetchBBKNNDetails(ctx)
      },
    },
    harmony_point : {
      description: 'Look up Harmony Data',
      type: new GraphQLList(HarmonyType),

      args: {
        cell_id: { type: GraphQLString },
        x_value: { type: GraphQLFloat },
        y_value: { type: GraphQLFloat },
      },
      resolve: (obj, args, ctx) => {
        return fetchHarmonyDetails(ctx)
      },
    },
    rna_point : {
      description: 'Look up RNA Data',
      type: new GraphQLList(RNAType),

      args: {
        cell_id: { type: GraphQLString },
        x_value: { type: GraphQLFloat },
        y_value: { type: GraphQLFloat },
      },
      resolve: (obj, args, ctx) => {
        return fetchRNADetails(ctx)
      },
    },
    scanorama_point : {
      description: 'Look up Scanorama Data',
      type: new GraphQLList(ScanoramaType),

      args: {
        cell_id: { type: GraphQLString },
        x_value: { type: GraphQLFloat },
        y_value: { type: GraphQLFloat },
      },
      resolve: (obj, args, ctx) => {
        return fetchScanoramaDetails(ctx)
      },
    },
    cell_type_point : {
      description: 'Look up Cell Type Data',
      type: new GraphQLList(CellTypeType),

      args: {
        cell_id: { type: GraphQLString },
        bbknn_type: { type: GraphQLString },
        harmony_type: { type: GraphQLString },
        scanorama_type: { type: GraphQLString },
      },
      resolve: (obj, args, ctx) => {
        return fetchCellTypeDetails(ctx)
      },
    },
    metadata_point : {
      description: 'Look up Metadata',
      type: new GraphQLList(MetadataType),

      args: {
        cell_id: { type: GraphQLString },
        age: { type: GraphQLString },
        sex: { type: GraphQLString },
      },
      resolve: (obj, args, ctx) => {
        return fetchMetadataDetails(ctx)
      },
    },

    /*
    expression_point : {
      description: 'Look up Expression Data',
      type: new GraphQLList(ExpressionType),

      args: {
        gene_id: { type: GraphQLString },
        Thoc1: { type: GraphQLFloat },
        A930011O12Rik: { type: GraphQLFloat },
        Grik3: { type: GraphQLFloat },
        Gm22854: { type: GraphQLFloat },
        Trim25: { type: GraphQLFloat },
        Mir378b: { type: GraphQLFloat },
        Tsnax: { type: GraphQLFloat },
        Gtf3c1: { type: GraphQLFloat },
        Usp33: { type: GraphQLFloat },
        C1ql1: { type: GraphQLFloat },
        _1600029D21Rik: { type: GraphQLFloat },
        Clec3b: { type: GraphQLFloat },
        Gm6559: { type: GraphQLFloat },
        Hmgxb3: { type: GraphQLFloat },
        _1700001L19Rik: { type: GraphQLFloat },
        FAS_AS1: { type: GraphQLFloat },
        Prkg1: { type: GraphQLFloat },
        Gm11273: { type: GraphQLFloat },
        Cilp2: { type: GraphQLFloat },
        Map6: { type: GraphQLFloat },
        Egr1: { type: GraphQLFloat },
        Gm3033: { type: GraphQLFloat },
        Fcgr3: { type: GraphQLFloat },
        Gm6135: { type: GraphQLFloat },
        Gm24492: { type: GraphQLFloat },
        Shh: { type: GraphQLFloat },
        Stra8: { type: GraphQLFloat },
        Exog: { type: GraphQLFloat },
        Gm24920: { type: GraphQLFloat },
        Ctsb: { type: GraphQLFloat },
        Prm3: { type: GraphQLFloat },
        Dcp1b: { type: GraphQLFloat },
        Ankmy2: { type: GraphQLFloat },
        Gm12629: { type: GraphQLFloat },
        Gm20531: { type: GraphQLFloat },
        Cd209g: { type: GraphQLFloat },
        Gm26681: { type: GraphQLFloat },
        Arhgef11: { type: GraphQLFloat },
        Spg11: { type: GraphQLFloat },
        Hapln4: { type: GraphQLFloat },
        Gpd2: { type: GraphQLFloat },
        Amacr: { type: GraphQLFloat },
        Gm12224: { type: GraphQLFloat },
        Prox2os: { type: GraphQLFloat },
        Trmt2a: { type: GraphQLFloat },
        Rad54l: { type: GraphQLFloat },
        Bpgm: { type: GraphQLFloat },
        Gm839: { type: GraphQLFloat },
        Pnpla7: { type: GraphQLFloat },
        Ngly1: { type: GraphQLFloat },
        Gm11377: { type: GraphQLFloat },
        Gm24665: { type: GraphQLFloat },
        Ighv3_8: { type: GraphQLFloat },
        _1700009N14Rik: { type: GraphQLFloat },
        _2500002B13Rik: { type: GraphQLFloat },
        Dxo: { type: GraphQLFloat },
        Dtna: { type: GraphQLFloat },
        Cd38: { type: GraphQLFloat },
        Trav18: { type: GraphQLFloat },
        Gpr110: { type: GraphQLFloat },
        Gm21060: { type: GraphQLFloat },
        _4921539H07Rik: { type: GraphQLFloat },
        Gm10860: { type: GraphQLFloat },
        _1700031F05Rik: { type: GraphQLFloat },
        Ifit1bl2: { type: GraphQLFloat },
        Iltifb: { type: GraphQLFloat },
        Ermp1: { type: GraphQLFloat },
        Zfp322a: { type: GraphQLFloat },
        Gm24650: { type: GraphQLFloat },
        Gm11646: { type: GraphQLFloat },
        _4931413I07Rik: { type: GraphQLFloat },
        Ube2z: { type: GraphQLFloat },
        Gm9742: { type: GraphQLFloat },
        Saa1: { type: GraphQLFloat },
        Chrd: { type: GraphQLFloat },
        Gm15963: { type: GraphQLFloat },
        Muc19: { type: GraphQLFloat },
        Amy1: { type: GraphQLFloat },
        Ric8b: { type: GraphQLFloat },
        Gm23940: { type: GraphQLFloat },
        Loxl4: { type: GraphQLFloat },
        Gm14434: { type: GraphQLFloat },
        Traj7: { type: GraphQLFloat },
        Gm904: { type: GraphQLFloat },
        Tia1: { type: GraphQLFloat },
        Dnase2a: { type: GraphQLFloat },
        Cracr2a: { type: GraphQLFloat },
        Nars: { type: GraphQLFloat },
        Akap12: { type: GraphQLFloat },
        Aldh5a1: { type: GraphQLFloat },
        Apobr: { type: GraphQLFloat },
        Adam6a: { type: GraphQLFloat },
        Hilpda: { type: GraphQLFloat },
        Rpl37: { type: GraphQLFloat },
        Mcemp1: { type: GraphQLFloat },
        Gm21811: { type: GraphQLFloat },
        _1700084C01Rik: { type: GraphQLFloat },
        Gm16578: { type: GraphQLFloat },
        Igkv3_2: { type: GraphQLFloat },
        Hcn2: { type: GraphQLFloat },
        Yipf2: { type: GraphQLFloat },
        Fam195a: { type: GraphQLFloat },
        E330020D12Rik: { type: GraphQLFloat },
        Abca6: { type: GraphQLFloat },
        Rin3: { type: GraphQLFloat },
        Ap5z1: { type: GraphQLFloat },
        Tmem222: { type: GraphQLFloat },
        _4921514A10Rik: { type: GraphQLFloat },
        Chd6: { type: GraphQLFloat },
        Chpt1: { type: GraphQLFloat },
        mmu_mir_6375: { type: GraphQLFloat },
        Gm4876: { type: GraphQLFloat },
        Adh5: { type: GraphQLFloat },
        Ptprj: { type: GraphQLFloat },
        Fam174a: { type: GraphQLFloat },
        Pccb: { type: GraphQLFloat },
        Skap2: { type: GraphQLFloat },
        Celsr1: { type: GraphQLFloat },
        Hspa1a: { type: GraphQLFloat },
        Gm2800: { type: GraphQLFloat },
        Ubash3b: { type: GraphQLFloat },
        Tnk2: { type: GraphQLFloat },
        _1600020E01Rik: { type: GraphQLFloat },
        Vamp7: { type: GraphQLFloat },
        Gm10676: { type: GraphQLFloat },
        Cd2: { type: GraphQLFloat },
        Gm23883: { type: GraphQLFloat },
        Sulf1: { type: GraphQLFloat },
        Gsta1: { type: GraphQLFloat },
        Frmd5: { type: GraphQLFloat },
        Trim63: { type: GraphQLFloat },
        Lipa: { type: GraphQLFloat },
        Hist1h2bg: { type: GraphQLFloat },
        Gm12473: { type: GraphQLFloat },
        Gm26378: { type: GraphQLFloat },
        Neurl1a: { type: GraphQLFloat },
        Gm28086: { type: GraphQLFloat },
        Mir186: { type: GraphQLFloat },
        Gabrr1: { type: GraphQLFloat },
        Gm13556: { type: GraphQLFloat },
        Sostdc1: { type: GraphQLFloat },
        Gm26751: { type: GraphQLFloat },
        Orai3: { type: GraphQLFloat },
        Pth2: { type: GraphQLFloat },
        Lilr4b: { type: GraphQLFloat },
        Cyp4a12b: { type: GraphQLFloat },
        Gm29187: { type: GraphQLFloat },
        Gm13575: { type: GraphQLFloat },
        Atxn7l3b: { type: GraphQLFloat },
        Dip2b: { type: GraphQLFloat },
        Gm26636: { type: GraphQLFloat },
        mmu_mir_7036: { type: GraphQLFloat },
        _4930556M19Rik: { type: GraphQLFloat },
        Trim7: { type: GraphQLFloat },
        Olfr923: { type: GraphQLFloat },
        _9430016H08Rik: { type: GraphQLFloat },
        Gm13174: { type: GraphQLFloat },
        Peli1: { type: GraphQLFloat },
        Ehmt2: { type: GraphQLFloat },
        Fam177a: { type: GraphQLFloat },
        Ppef1: { type: GraphQLFloat },
        Vdac3_ps1: { type: GraphQLFloat },
        Gm24854: { type: GraphQLFloat },
        Zfp212: { type: GraphQLFloat },
        Gm17168: { type: GraphQLFloat },
        Gata5: { type: GraphQLFloat },
        BC051077: { type: GraphQLFloat },
        Klre1: { type: GraphQLFloat },
        Gm13833: { type: GraphQLFloat },
        Gm24336: { type: GraphQLFloat },
        Pak7: { type: GraphQLFloat },
        Cxxc5: { type: GraphQLFloat },
        Rasa1: { type: GraphQLFloat },
        Cr2: { type: GraphQLFloat },
        Ap3s1: { type: GraphQLFloat },
        Myo6: { type: GraphQLFloat },
        Arrdc1: { type: GraphQLFloat },
        Dpy19l4: { type: GraphQLFloat },
        Xpo6: { type: GraphQLFloat },
        Slc37a1: { type: GraphQLFloat },
        Nkd2: { type: GraphQLFloat },
        Ndufb2: { type: GraphQLFloat },
        Lpin2: { type: GraphQLFloat },
        Gm26327: { type: GraphQLFloat },
        Galp: { type: GraphQLFloat },
        Gm9951: { type: GraphQLFloat },
        _4930406D18Rik: { type: GraphQLFloat },
        Dennd1c: { type: GraphQLFloat },
        Hnrnpc: { type: GraphQLFloat },
        Gm15755: { type: GraphQLFloat },
        Lad1: { type: GraphQLFloat },
        Gm9041: { type: GraphQLFloat },
        Rnf2: { type: GraphQLFloat },
        H2_Ob: { type: GraphQLFloat },
        Rbm41: { type: GraphQLFloat },
        Gm11959: { type: GraphQLFloat },
        Gm26554: { type: GraphQLFloat },
        Hist2h3c1: { type: GraphQLFloat },
        Dock1: { type: GraphQLFloat },
        Gm25997: { type: GraphQLFloat },
        Adam12: { type: GraphQLFloat },
        Gm23946: { type: GraphQLFloat },
        Papolg: { type: GraphQLFloat },
        Cct4: { type: GraphQLFloat },
        S100a7a: { type: GraphQLFloat },
        Gm22301: { type: GraphQLFloat },
        Dffa: { type: GraphQLFloat },
        Gm22004: { type: GraphQLFloat },
        Fabp3_ps1: { type: GraphQLFloat },
        _4930465M20Rik: { type: GraphQLFloat },
        BC016423: { type: GraphQLFloat },
        Ap2a2: { type: GraphQLFloat },
        Sema6b: { type: GraphQLFloat },
        Rnf181: { type: GraphQLFloat },
        Clec4e: { type: GraphQLFloat },
        Pla1a: { type: GraphQLFloat },
        Gm24971: { type: GraphQLFloat },
        Ttc21b: { type: GraphQLFloat },
        Gm25291: { type: GraphQLFloat },
        Ankrd1: { type: GraphQLFloat },
        A930016O22Rik: { type: GraphQLFloat },
        Ngfr: { type: GraphQLFloat },
        Peli2: { type: GraphQLFloat },
        Cntfr: { type: GraphQLFloat },
        Fbxl16: { type: GraphQLFloat },
        Atf5: { type: GraphQLFloat },
        Bmp1: { type: GraphQLFloat },
        AI838599: { type: GraphQLFloat },
        Grcc10: { type: GraphQLFloat },
        RP23_466J17_3: { type: GraphQLFloat },
        R3hcc1: { type: GraphQLFloat },
        Gm23209: { type: GraphQLFloat },
        Ppp2ca: { type: GraphQLFloat },
        Kifc1: { type: GraphQLFloat },
        Irak1bp1: { type: GraphQLFloat },
        Fam210a: { type: GraphQLFloat },
        Arl14ep: { type: GraphQLFloat },
        Apip: { type: GraphQLFloat },
        Gm29018: { type: GraphQLFloat },
        Dnah5: { type: GraphQLFloat },
        Pir: { type: GraphQLFloat },
        Cdk1: { type: GraphQLFloat },
        Hsd17b6: { type: GraphQLFloat },
        _2310036O22Rik: { type: GraphQLFloat },
        Pkp3: { type: GraphQLFloat },
        Mrps30: { type: GraphQLFloat },
        Rad51b: { type: GraphQLFloat },
        Gm23588: { type: GraphQLFloat },
        _4930550L24Rik: { type: GraphQLFloat },
        Ramp1: { type: GraphQLFloat },
        Ube2cbp: { type: GraphQLFloat },
        Copg2: { type: GraphQLFloat },
        Gm26762: { type: GraphQLFloat },
        Fat4: { type: GraphQLFloat },
        Gm16845: { type: GraphQLFloat },
        Ap4m1: { type: GraphQLFloat },
        Gm15889: { type: GraphQLFloat },
        Nxpe4: { type: GraphQLFloat },
        Gm22314: { type: GraphQLFloat },
        Gm26410: { type: GraphQLFloat },
        Gm11706: { type: GraphQLFloat },
        Tmprss9: { type: GraphQLFloat },
        Gm9900: { type: GraphQLFloat },
        _4933404K08Rik: { type: GraphQLFloat },
        Bdp1: { type: GraphQLFloat },
        Gm12590: { type: GraphQLFloat },
        Tmem129: { type: GraphQLFloat },
        Ccer2: { type: GraphQLFloat },
        Ccdc83: { type: GraphQLFloat },
        Ero1l: { type: GraphQLFloat },
        Gm24729: { type: GraphQLFloat },
        _9430024E24Rik: { type: GraphQLFloat },
        Xntrpc: { type: GraphQLFloat },
        RP23_148P22_1: { type: GraphQLFloat },
        Gm26565: { type: GraphQLFloat },
        Pcdhb5: { type: GraphQLFloat },
        Safb: { type: GraphQLFloat },
        Gm12146: { type: GraphQLFloat },
        Gm23377: { type: GraphQLFloat },
        Gm20497: { type: GraphQLFloat },
        Epha2: { type: GraphQLFloat },
        Pcdhga12: { type: GraphQLFloat },
        Fam96b: { type: GraphQLFloat },
        Drc1: { type: GraphQLFloat },
        Usp28: { type: GraphQLFloat },
        Fgf13: { type: GraphQLFloat },
        Gm44169: { type: GraphQLFloat },
        Rnf214: { type: GraphQLFloat },
        Csnk1g3: { type: GraphQLFloat },
        Gm10719: { type: GraphQLFloat },
        _9330182O14Rik: { type: GraphQLFloat },
        Trim9: { type: GraphQLFloat },
        Mir342: { type: GraphQLFloat },
        Gm16325: { type: GraphQLFloat },
        Gm3404: { type: GraphQLFloat },
        _4930529M08Rik: { type: GraphQLFloat },
        Gm43351: { type: GraphQLFloat },
        Kcnk3: { type: GraphQLFloat },
        Gm25014: { type: GraphQLFloat },
        Tpi1: { type: GraphQLFloat },
        n_R5s151: { type: GraphQLFloat },
        Dnaaf1: { type: GraphQLFloat },
        Tmem252: { type: GraphQLFloat },
        Ccdc158: { type: GraphQLFloat },
        _1810020O05Rik: { type: GraphQLFloat },
        Kif2c: { type: GraphQLFloat },
        Hoxb6: { type: GraphQLFloat },
        Cryba1: { type: GraphQLFloat },
        Lrrc40: { type: GraphQLFloat },
        _9230104M06Rik: { type: GraphQLFloat },
        Ptrhd1: { type: GraphQLFloat },
        H2_M10_3: { type: GraphQLFloat },
        Gm24019: { type: GraphQLFloat },
        Nyap2: { type: GraphQLFloat },
        Gldn: { type: GraphQLFloat },
        Aqp3: { type: GraphQLFloat },
        Gpr56: { type: GraphQLFloat },
        Capsl: { type: GraphQLFloat },
        Nckap5l: { type: GraphQLFloat },
        Fsip2: { type: GraphQLFloat },
        Asb18: { type: GraphQLFloat },
        Zfp28: { type: GraphQLFloat },
        _4921522P10Rik: { type: GraphQLFloat },
        Btg1: { type: GraphQLFloat },
        Acsm4: { type: GraphQLFloat },
        Fam132b: { type: GraphQLFloat },
        Tnpo2: { type: GraphQLFloat },
        Bach2os: { type: GraphQLFloat },
        Banp: { type: GraphQLFloat },
        Gm10818: { type: GraphQLFloat },
        Vps50: { type: GraphQLFloat },
        Tmem255b: { type: GraphQLFloat },
        Gm16116: { type: GraphQLFloat },
        Scap: { type: GraphQLFloat },
        Gm22114: { type: GraphQLFloat },
        Tspan13: { type: GraphQLFloat },
        Gm14230: { type: GraphQLFloat },
        Eif3a: { type: GraphQLFloat },
        Lamc2: { type: GraphQLFloat },
        Adgrg3: { type: GraphQLFloat },
        Lrrc58: { type: GraphQLFloat },
        Gm10775: { type: GraphQLFloat },
        Gjc1: { type: GraphQLFloat },
        Gm5878: { type: GraphQLFloat },
        _2810001G20Rik: { type: GraphQLFloat },
        Gm9961: { type: GraphQLFloat },
        Gm16432: { type: GraphQLFloat },
        Cphx2: { type: GraphQLFloat },
        Elk3: { type: GraphQLFloat },
        Gm37027: { type: GraphQLFloat },
        Gtsf1l: { type: GraphQLFloat },
        Gm26756: { type: GraphQLFloat },
        A330048O09Rik: { type: GraphQLFloat },
        Gm11586: { type: GraphQLFloat },
        Gm26606: { type: GraphQLFloat },
        Gm12406: { type: GraphQLFloat },
        Gm8923: { type: GraphQLFloat },
        Gmcl1: { type: GraphQLFloat },
        Onecut1: { type: GraphQLFloat },
        Cntn1: { type: GraphQLFloat },
        Nmd3: { type: GraphQLFloat },
        Skint11: { type: GraphQLFloat },
        Slc25a14: { type: GraphQLFloat },
        Sult4a1: { type: GraphQLFloat },
        Tfap2b: { type: GraphQLFloat },
        _9630033F20Rik: { type: GraphQLFloat },
        Haao: { type: GraphQLFloat },
        Gm10799: { type: GraphQLFloat },
        Fam47e: { type: GraphQLFloat },
        Unc45a: { type: GraphQLFloat },
        Gm20731: { type: GraphQLFloat },
        Pdyn: { type: GraphQLFloat },
        Lacc1: { type: GraphQLFloat },
        Gm15417: { type: GraphQLFloat },
        Terf2: { type: GraphQLFloat },
        Fbxo2: { type: GraphQLFloat },
        Gm26640: { type: GraphQLFloat },
        Unc13b: { type: GraphQLFloat },
        Nkiras1: { type: GraphQLFloat },
        Gm16152: { type: GraphQLFloat },
        Guca1b: { type: GraphQLFloat },
        Fgfr4: { type: GraphQLFloat },
        Slmap: { type: GraphQLFloat },
        Hba_a1: { type: GraphQLFloat },
        C230035I16Rik: { type: GraphQLFloat },
        Gm24530: { type: GraphQLFloat },
        _4930432E11Rik: { type: GraphQLFloat },
        Hdac7: { type: GraphQLFloat },
        Pcdhgb6: { type: GraphQLFloat },
        BC049762: { type: GraphQLFloat },
        Mrps18a: { type: GraphQLFloat },
        Gm5356: { type: GraphQLFloat },
        Gm43660: { type: GraphQLFloat },
        Rpl5: { type: GraphQLFloat },
        Il1rl1: { type: GraphQLFloat },
        Ccdc104: { type: GraphQLFloat },
        Mitd1: { type: GraphQLFloat },
        Ogdhl: { type: GraphQLFloat },
        Utrn: { type: GraphQLFloat },
        Scai: { type: GraphQLFloat },
        Gm17039: { type: GraphQLFloat },
        Ldb3: { type: GraphQLFloat },
        Gm24271: { type: GraphQLFloat },
        Gm13187: { type: GraphQLFloat },
        Mir124_2hg: { type: GraphQLFloat },
        Riiad1: { type: GraphQLFloat },
        Zbtb7b: { type: GraphQLFloat },
        Nudcd3: { type: GraphQLFloat },
        Dhodh: { type: GraphQLFloat },
        Cacna2d3: { type: GraphQLFloat },
        Kcns2: { type: GraphQLFloat },
        Gm42560: { type: GraphQLFloat },
        Rasal3: { type: GraphQLFloat },
        Gm561: { type: GraphQLFloat },
        _5730412P04Rik: { type: GraphQLFloat },
        Gli2: { type: GraphQLFloat },
        Pomt2: { type: GraphQLFloat },
        _1700014D04Rik: { type: GraphQLFloat },
        Limk2: { type: GraphQLFloat },
        Apof: { type: GraphQLFloat },
        Gm648: { type: GraphQLFloat },
        Ugt1a6b: { type: GraphQLFloat },
        Gm5424: { type: GraphQLFloat },
        mmu_mir_7078: { type: GraphQLFloat },
        Mxra7: { type: GraphQLFloat },
        Gm11413: { type: GraphQLFloat },
        Thumpd1: { type: GraphQLFloat },
        Asz1: { type: GraphQLFloat },
        L3mbtl4: { type: GraphQLFloat },
        Atp6v1g2: { type: GraphQLFloat },
        Cntn6: { type: GraphQLFloat },
        Adal: { type: GraphQLFloat },
        Lin28a: { type: GraphQLFloat },
        Lipm: { type: GraphQLFloat },
        Samd4b: { type: GraphQLFloat },
        Gab3: { type: GraphQLFloat },
        Gm23846: { type: GraphQLFloat },
        Zfp541: { type: GraphQLFloat },
        Ccdc151: { type: GraphQLFloat },
        Ldhc: { type: GraphQLFloat },
        Gm25980: { type: GraphQLFloat },
        Large: { type: GraphQLFloat },
        Snord100: { type: GraphQLFloat },
        Zfp3: { type: GraphQLFloat },
        Bcl3: { type: GraphQLFloat },
        Gm12660: { type: GraphQLFloat },
        Cryz: { type: GraphQLFloat },
        Ankrd33b: { type: GraphQLFloat },
        _4930564K09Rik: { type: GraphQLFloat },
        Col9a2: { type: GraphQLFloat },
        Colgalt2: { type: GraphQLFloat },
        AC121131_2: { type: GraphQLFloat },
        Psmg2: { type: GraphQLFloat },
        Ifi44l: { type: GraphQLFloat },
        Sh2b2: { type: GraphQLFloat },
        Prkci: { type: GraphQLFloat },
        Abcc6: { type: GraphQLFloat },
        Gm6337: { type: GraphQLFloat },
        Mast1: { type: GraphQLFloat },
        Lsp1: { type: GraphQLFloat },
        Gm26658: { type: GraphQLFloat },
        Ighv1_82: { type: GraphQLFloat },
        Gm25451: { type: GraphQLFloat },
        Eif4a1: { type: GraphQLFloat },
        _5430421N21Rik: { type: GraphQLFloat },
        Nav3: { type: GraphQLFloat },
        Gfra1: { type: GraphQLFloat },
        Gm26132: { type: GraphQLFloat },
        Igkj5: { type: GraphQLFloat },
        _4732491K20Rik: { type: GraphQLFloat },
        Trip6: { type: GraphQLFloat },
        Gm22994: { type: GraphQLFloat },
        Sestd1: { type: GraphQLFloat },
        Xpo4: { type: GraphQLFloat },
        Trim58: { type: GraphQLFloat },
        Gm13748: { type: GraphQLFloat },
        Sun2: { type: GraphQLFloat },
        Gm43159: { type: GraphQLFloat },
        Tespa1: { type: GraphQLFloat },
        Ralgapb: { type: GraphQLFloat },
        Atp5j2: { type: GraphQLFloat },
        Ush2a: { type: GraphQLFloat },
        Padi3: { type: GraphQLFloat },
        Chrm5: { type: GraphQLFloat },
        Galr2: { type: GraphQLFloat },
        Bglap2: { type: GraphQLFloat },
        _4930451G09Rik: { type: GraphQLFloat },
        Tnks2: { type: GraphQLFloat },
        Ddx49: { type: GraphQLFloat },
        Snord104: { type: GraphQLFloat },
        Ap3m2: { type: GraphQLFloat },
        Rtp2: { type: GraphQLFloat },
        C4bp: { type: GraphQLFloat },
        Rab20: { type: GraphQLFloat },
        N6amt1: { type: GraphQLFloat },
        _1700021F13Rik: { type: GraphQLFloat },
        Ifna7: { type: GraphQLFloat },
        Lmcd1: { type: GraphQLFloat },
        Adgrg2: { type: GraphQLFloat },
        Apmap: { type: GraphQLFloat },
        Col20a1: { type: GraphQLFloat },
        _5033430I15Rik: { type: GraphQLFloat },
        Gm5132: { type: GraphQLFloat },
        Slc27a1: { type: GraphQLFloat },
        Gm23634: { type: GraphQLFloat },
        Gm15133: { type: GraphQLFloat },
        Ampd1: { type: GraphQLFloat },
        Lsm8: { type: GraphQLFloat },
        Hist1h4f: { type: GraphQLFloat },
        Plp2: { type: GraphQLFloat },
        Ostm1: { type: GraphQLFloat },
        C86695: { type: GraphQLFloat },
        Dhdh: { type: GraphQLFloat },
        Ppil1: { type: GraphQLFloat },
        Raet1e: { type: GraphQLFloat },
        _9530085P06Rik: { type: GraphQLFloat },
        Gpr61: { type: GraphQLFloat },
        Gm10558: { type: GraphQLFloat },
        Cldnd2: { type: GraphQLFloat },
        Gm12446: { type: GraphQLFloat },
        Gm16039: { type: GraphQLFloat },
        Gm26643: { type: GraphQLFloat },
        Xpo1: { type: GraphQLFloat },
        Nupl1: { type: GraphQLFloat },
        Mir702: { type: GraphQLFloat },
        Olfr554: { type: GraphQLFloat },
        Wfikkn2: { type: GraphQLFloat },
        Smim6: { type: GraphQLFloat },
        Brms1l: { type: GraphQLFloat },
        Mall: { type: GraphQLFloat },
        Sec14l5: { type: GraphQLFloat },
        Ngp: { type: GraphQLFloat },
        Atp5l: { type: GraphQLFloat },
        Gm7160: { type: GraphQLFloat },
        Ccdc184: { type: GraphQLFloat },
        Mir1957: { type: GraphQLFloat },
        Gm11261: { type: GraphQLFloat },
        Gm15672: { type: GraphQLFloat },
        Flcn: { type: GraphQLFloat },
        Gbp11: { type: GraphQLFloat },
        Tmem181b_ps_1: { type: GraphQLFloat },
        Gpr26: { type: GraphQLFloat },
        Gm22070: { type: GraphQLFloat },
        Gckr: { type: GraphQLFloat },
        Gstm5: { type: GraphQLFloat },
        Ticrr: { type: GraphQLFloat },
        Kcnmb4os1: { type: GraphQLFloat },
        BC005561: { type: GraphQLFloat },
        Gm23247: { type: GraphQLFloat },
        Gm9964: { type: GraphQLFloat },
        DQ267102: { type: GraphQLFloat },
        Ipo5: { type: GraphQLFloat },
        Taf7: { type: GraphQLFloat },
        Gm13446: { type: GraphQLFloat },
        Gm24311: { type: GraphQLFloat },
        B230118H07Rik: { type: GraphQLFloat },
        Mgat4a: { type: GraphQLFloat },
        Rdh19: { type: GraphQLFloat },
        RP23_198F11_3: { type: GraphQLFloat },
        Nxph2: { type: GraphQLFloat },
        Gm12694: { type: GraphQLFloat },
        Mamdc2: { type: GraphQLFloat },
        Wdr7: { type: GraphQLFloat },
        Exoc6: { type: GraphQLFloat },
        Kitl: { type: GraphQLFloat },
        Aida: { type: GraphQLFloat },
        Rfc3: { type: GraphQLFloat },
        C430014B12Rik: { type: GraphQLFloat },
        A730098A19Rik: { type: GraphQLFloat },
        Pappa2: { type: GraphQLFloat },
        Npsr1: { type: GraphQLFloat },
        Tmem52: { type: GraphQLFloat },
        Mterfd2: { type: GraphQLFloat },
        Snora69: { type: GraphQLFloat },
        Cped1: { type: GraphQLFloat },
        D3Bwg0562e: { type: GraphQLFloat },
        Gm16725: { type: GraphQLFloat },
        N6amt2: { type: GraphQLFloat },
        Gm11842: { type: GraphQLFloat },
        Psmg1: { type: GraphQLFloat },
        Pts: { type: GraphQLFloat },
        Erich1: { type: GraphQLFloat },
        Zmym6: { type: GraphQLFloat },
        Bcl2l11: { type: GraphQLFloat },
        Hist1h4j: { type: GraphQLFloat },
        Gm24552: { type: GraphQLFloat },
        Spib: { type: GraphQLFloat },
        _9430021M05Rik: { type: GraphQLFloat },
        D430041D05Rik: { type: GraphQLFloat },
        Sarnp: { type: GraphQLFloat },
        _2010110K18Rik: { type: GraphQLFloat },
        Rufy4: { type: GraphQLFloat },
        Vamp5: { type: GraphQLFloat },
        mmu_mir_6351: { type: GraphQLFloat },
        Gm10840: { type: GraphQLFloat },
        Cd70: { type: GraphQLFloat },
        _9130604C24Rik: { type: GraphQLFloat },
        Nat1: { type: GraphQLFloat },
        Tardbp: { type: GraphQLFloat },
        Rap2b: { type: GraphQLFloat },
        Tecpr2: { type: GraphQLFloat },
        Gm1720: { type: GraphQLFloat },
        B230307C23Rik: { type: GraphQLFloat },
        _4930577N17Rik: { type: GraphQLFloat },
        Phf2: { type: GraphQLFloat },
        Gm11549: { type: GraphQLFloat },
        Frmd7: { type: GraphQLFloat },
        _2810471M01Rik: { type: GraphQLFloat },
        Sult1e1: { type: GraphQLFloat },
        Zfp275: { type: GraphQLFloat },
        Tmco2: { type: GraphQLFloat },
        Mamld1: { type: GraphQLFloat },
        Mrpl51: { type: GraphQLFloat },
        Epg5: { type: GraphQLFloat },
        Rpl27: { type: GraphQLFloat },
        Hypm: { type: GraphQLFloat },
        Gm13564: { type: GraphQLFloat },
        Grin2d: { type: GraphQLFloat },
        Tmem25: { type: GraphQLFloat },
        Gm22862: { type: GraphQLFloat },
        Tm4sf4: { type: GraphQLFloat },
        Eef2k: { type: GraphQLFloat },
        Vdac1: { type: GraphQLFloat },
        Pole2: { type: GraphQLFloat },
        Ppapdc2: { type: GraphQLFloat },
        Cmtr2: { type: GraphQLFloat },
        Aoc1: { type: GraphQLFloat },
        _1700028N14Rik: { type: GraphQLFloat },
        Ulk3: { type: GraphQLFloat },
        Gch1: { type: GraphQLFloat },
        Hrct1: { type: GraphQLFloat },
        Aldh6a1: { type: GraphQLFloat },
        C87198: { type: GraphQLFloat },
        Tsen54: { type: GraphQLFloat },
        Gm23820: { type: GraphQLFloat },
        Hsd11b1: { type: GraphQLFloat },
        H60b: { type: GraphQLFloat },
        Fsip1: { type: GraphQLFloat },
        Gm16275: { type: GraphQLFloat },
        Mrpl38: { type: GraphQLFloat },
        Mir1981: { type: GraphQLFloat },
        Hist1h4i: { type: GraphQLFloat },
        Ighv6_6: { type: GraphQLFloat },
        _1700029J03Rik: { type: GraphQLFloat },
        Ndrg2: { type: GraphQLFloat },
        Nup62: { type: GraphQLFloat },
        Cacng5: { type: GraphQLFloat },
        Cstf2: { type: GraphQLFloat },
        Snupn: { type: GraphQLFloat },
        Ovgp1: { type: GraphQLFloat },
        _2310015K22Rik: { type: GraphQLFloat },
        Mrc1: { type: GraphQLFloat },
        Gm9990: { type: GraphQLFloat },
        Josd1: { type: GraphQLFloat },
        A230020J21Rik: { type: GraphQLFloat },
        Gm26544: { type: GraphQLFloat },
        B230334C09Rik: { type: GraphQLFloat },
        Gm28087: { type: GraphQLFloat },
        Edem2: { type: GraphQLFloat },
        Iglv3: { type: GraphQLFloat },
        AI837181: { type: GraphQLFloat },
        Gm16124: { type: GraphQLFloat },
        Gm43087: { type: GraphQLFloat },
        Mir432: { type: GraphQLFloat },
        Pank2: { type: GraphQLFloat },
        Gm44368: { type: GraphQLFloat },
        Lrrc74a: { type: GraphQLFloat },
        Gpat4: { type: GraphQLFloat },
        Gm8066: { type: GraphQLFloat },
        Fam199x: { type: GraphQLFloat },
        Usp17lc: { type: GraphQLFloat },
        Glis2: { type: GraphQLFloat },
        Uqcrb: { type: GraphQLFloat },
        Gm29367: { type: GraphQLFloat },
        Pmvk: { type: GraphQLFloat },
        Sept12: { type: GraphQLFloat },
        Gm26187: { type: GraphQLFloat },
        mmu_mir_8094: { type: GraphQLFloat },
        Pabpc1l: { type: GraphQLFloat },
        Ocln: { type: GraphQLFloat },
        AC167724_1: { type: GraphQLFloat },
        Gm13982: { type: GraphQLFloat },
        Vipas39: { type: GraphQLFloat },
        Zfp207: { type: GraphQLFloat },
        Traj28: { type: GraphQLFloat },
        Platr29: { type: GraphQLFloat },
        Tll2: { type: GraphQLFloat },
        Gm21958: { type: GraphQLFloat },
        Aldh4a1: { type: GraphQLFloat },
        Hp1bp3: { type: GraphQLFloat },
        Mir1936: { type: GraphQLFloat },
        Epha4: { type: GraphQLFloat },
        Hebp2: { type: GraphQLFloat },
        Ribc2: { type: GraphQLFloat },
        Dgkk: { type: GraphQLFloat },
        Gm26596: { type: GraphQLFloat },
        Gm3848: { type: GraphQLFloat },
        Gm10220: { type: GraphQLFloat },
        Gm15983: { type: GraphQLFloat },
        Mgarp: { type: GraphQLFloat },
        Gm10263: { type: GraphQLFloat },
        Ctsa: { type: GraphQLFloat },
        Rrp36: { type: GraphQLFloat },
        _2610204G07Rik: { type: GraphQLFloat },
        Upk1b: { type: GraphQLFloat },
        Chrac1: { type: GraphQLFloat },
        BC005624: { type: GraphQLFloat },
        Ttc7: { type: GraphQLFloat },
        Rufy1: { type: GraphQLFloat },
        Romo1: { type: GraphQLFloat },
        Gm26441: { type: GraphQLFloat },
        Snord58b: { type: GraphQLFloat },
        Cuzd1: { type: GraphQLFloat },
        Pik3cg: { type: GraphQLFloat },
        _2700016F22Rik: { type: GraphQLFloat },
        Atp6ap1l: { type: GraphQLFloat },
        Ispd: { type: GraphQLFloat },
        Cacna1e: { type: GraphQLFloat },
        Lst1: { type: GraphQLFloat },
        Cox14: { type: GraphQLFloat },
        Gm22368: { type: GraphQLFloat },
        Gm24347: { type: GraphQLFloat },
        Mup4: { type: GraphQLFloat },
        Serpina9: { type: GraphQLFloat },
        Neil1: { type: GraphQLFloat },
        Kmt2e: { type: GraphQLFloat },
        Gm22790: { type: GraphQLFloat },
        Dst: { type: GraphQLFloat },
        _5830415F09Rik: { type: GraphQLFloat },
        Srd5a3: { type: GraphQLFloat },
        Hsd17b7: { type: GraphQLFloat },
        Gm14235: { type: GraphQLFloat },
        Zfp507: { type: GraphQLFloat },
        Wbscr22: { type: GraphQLFloat },
        Cstf1: { type: GraphQLFloat },
        Fmod: { type: GraphQLFloat },
        Gm10044: { type: GraphQLFloat },
        Gm13972: { type: GraphQLFloat },
        Tslp: { type: GraphQLFloat },
        Sptbn2: { type: GraphQLFloat },
        Dbnl: { type: GraphQLFloat },
        Trmt5: { type: GraphQLFloat },
        Tyw3: { type: GraphQLFloat },
        Larp7: { type: GraphQLFloat },
        Angpt2: { type: GraphQLFloat },
        Map7d1: { type: GraphQLFloat },
        Naa10: { type: GraphQLFloat },
        Zbtb26: { type: GraphQLFloat },
        _5330439A09Rik: { type: GraphQLFloat },
        _4930443B20Rik: { type: GraphQLFloat },
        Palm2: { type: GraphQLFloat },
        Gm26264: { type: GraphQLFloat },
        Gm10629: { type: GraphQLFloat },
        Ckmt2: { type: GraphQLFloat },
        Gsdma: { type: GraphQLFloat },
        RP23_235M8_7: { type: GraphQLFloat },
        Gltpd2: { type: GraphQLFloat },
        Polr3k: { type: GraphQLFloat },
        mmu_mir_7655: { type: GraphQLFloat },
        Gm11791: { type: GraphQLFloat },
        Gm26517: { type: GraphQLFloat },
        Mgat4c: { type: GraphQLFloat },
        Lonrf2: { type: GraphQLFloat },
        Gm10069: { type: GraphQLFloat },
        Gm5771: { type: GraphQLFloat },
        Timm21: { type: GraphQLFloat },
        Ptp4a3: { type: GraphQLFloat },
        Sytl3: { type: GraphQLFloat },
        Zfp729b: { type: GraphQLFloat },
        Gm20443: { type: GraphQLFloat },
        Slc9a3r1: { type: GraphQLFloat },
        Fbxw7: { type: GraphQLFloat },
        Nhlh2: { type: GraphQLFloat },
        Gm25905: { type: GraphQLFloat },
        Tnfsf11: { type: GraphQLFloat },
        Zfp955a: { type: GraphQLFloat },
        Izumo2: { type: GraphQLFloat },
        Gm25189: { type: GraphQLFloat },
        Tbl2: { type: GraphQLFloat },
        Fam219b: { type: GraphQLFloat },
        Ckap4: { type: GraphQLFloat },
        Smcp: { type: GraphQLFloat },
        _2810006K23Rik: { type: GraphQLFloat },
        Khsrp: { type: GraphQLFloat },
        Gm42423: { type: GraphQLFloat },
        Mtfp1: { type: GraphQLFloat },
        Ppp1r12b: { type: GraphQLFloat },
        Gm11351: { type: GraphQLFloat },
        Neu3: { type: GraphQLFloat },
        _9930013L23Rik: { type: GraphQLFloat },
        Gm25889: { type: GraphQLFloat },
        Gm25325: { type: GraphQLFloat },
        Pxylp1: { type: GraphQLFloat },
        Rfpl3s: { type: GraphQLFloat },
        _1810049J17Rik: { type: GraphQLFloat },
        Wdr13: { type: GraphQLFloat },
        Nek3: { type: GraphQLFloat },
        BC026590: { type: GraphQLFloat },
        Gm13625: { type: GraphQLFloat },
        Myadm: { type: GraphQLFloat },
        Gabarap: { type: GraphQLFloat },
        Trav8_1: { type: GraphQLFloat },
        Pald1: { type: GraphQLFloat },
        BC048644: { type: GraphQLFloat },
        Gm15485: { type: GraphQLFloat },
        Nf2: { type: GraphQLFloat },
        Gdpd2: { type: GraphQLFloat },
        _1700026J14Rik: { type: GraphQLFloat },
        Mpped2: { type: GraphQLFloat },
        Cnksr3: { type: GraphQLFloat },
        Flt3l: { type: GraphQLFloat },
        Skap1: { type: GraphQLFloat },
        Sf3b5: { type: GraphQLFloat },
        Fam122a: { type: GraphQLFloat },
        Traf3ip2: { type: GraphQLFloat },
        _1700022P22Rik: { type: GraphQLFloat },
        Gm22509: { type: GraphQLFloat },
        Rock1: { type: GraphQLFloat },
        Acoxl: { type: GraphQLFloat },
        Gm7628: { type: GraphQLFloat },
        Gm43086: { type: GraphQLFloat },
        Kmt2b: { type: GraphQLFloat },
        Prpf6: { type: GraphQLFloat },
        Bard1: { type: GraphQLFloat },
        Ctnnbip1: { type: GraphQLFloat },
        Ms4a5: { type: GraphQLFloat },
        Cacna1a: { type: GraphQLFloat },
        Ralgps2: { type: GraphQLFloat },
        Tlr1: { type: GraphQLFloat },
        AW822073: { type: GraphQLFloat },
        _5430402E10Rik: { type: GraphQLFloat },
        Gm12594: { type: GraphQLFloat },
        Gm23402: { type: GraphQLFloat },
        Efcab4a: { type: GraphQLFloat },
        Gm5160: { type: GraphQLFloat },
        Fam124b: { type: GraphQLFloat },
        Col9a1: { type: GraphQLFloat },
        Gm17252: { type: GraphQLFloat },
        Gm7967: { type: GraphQLFloat },
        Bcl2l2: { type: GraphQLFloat },
        Gemin6: { type: GraphQLFloat },
        Uap1l1: { type: GraphQLFloat },
        Syt12: { type: GraphQLFloat },
        _3830432H09Rik: { type: GraphQLFloat },
        Coa3: { type: GraphQLFloat },
        Hvcn1: { type: GraphQLFloat },
        Gm22980: { type: GraphQLFloat },
        Tac2: { type: GraphQLFloat },
        Fgf11: { type: GraphQLFloat },
        Borcs8: { type: GraphQLFloat },
        Pbx1: { type: GraphQLFloat },
        Gm7596: { type: GraphQLFloat },
        Dda1: { type: GraphQLFloat },
        Gm16339: { type: GraphQLFloat },
        Plac9a: { type: GraphQLFloat },
        Slc1a5: { type: GraphQLFloat },
        Cox5b: { type: GraphQLFloat },
        Ccdc117: { type: GraphQLFloat },
        Gm22214: { type: GraphQLFloat },
        Cgref1: { type: GraphQLFloat },
        D830039M14Rik: { type: GraphQLFloat },
        Bex2: { type: GraphQLFloat },
        _5430405H02Rik: { type: GraphQLFloat },
        Trim75: { type: GraphQLFloat },
        Gm20711: { type: GraphQLFloat },
        Arhgef3: { type: GraphQLFloat },
        Wtap: { type: GraphQLFloat },
        _1700120G11Rik: { type: GraphQLFloat },
        Zfp697: { type: GraphQLFloat },
        _1700109H08Rik: { type: GraphQLFloat },
        BC024978: { type: GraphQLFloat },
        Gm13028: { type: GraphQLFloat },
        Appl1: { type: GraphQLFloat },
        Gfra4: { type: GraphQLFloat },
        Rhbdl1: { type: GraphQLFloat },
        Egln1: { type: GraphQLFloat },
        Gapt: { type: GraphQLFloat },
        Tbc1d8: { type: GraphQLFloat },
        B230322F03Rik: { type: GraphQLFloat },
        Cyp2c50: { type: GraphQLFloat },
        Ifna6: { type: GraphQLFloat },
        Slc19a3: { type: GraphQLFloat },
        Gm26777: { type: GraphQLFloat },
        Cd59a: { type: GraphQLFloat },
        Krt9: { type: GraphQLFloat },
        _3110004A20Rik: { type: GraphQLFloat },
        RP23_296I6_12: { type: GraphQLFloat },
        Cfap43: { type: GraphQLFloat },
        Tfam: { type: GraphQLFloat },
        Cst3: { type: GraphQLFloat },
        Gm21983: { type: GraphQLFloat },
        Gm14204: { type: GraphQLFloat },
        Ano7: { type: GraphQLFloat },
        Tmc4: { type: GraphQLFloat },
        Gm22452: { type: GraphQLFloat },
        Vmn1r89: { type: GraphQLFloat },
        Nqo2: { type: GraphQLFloat },
        Espl1: { type: GraphQLFloat },
        AU018091: { type: GraphQLFloat },
        Jup: { type: GraphQLFloat },
        Mbp: { type: GraphQLFloat },
        Slamf1: { type: GraphQLFloat },
        Gm410: { type: GraphQLFloat },
        Rpl18a: { type: GraphQLFloat },
        Fgf18: { type: GraphQLFloat },
        Traf7: { type: GraphQLFloat },
        Gm23068: { type: GraphQLFloat },
        Ttc23: { type: GraphQLFloat },
        Cyp2e1: { type: GraphQLFloat },
        Polrmt: { type: GraphQLFloat },
        Fgf2os: { type: GraphQLFloat },
        Gm17172: { type: GraphQLFloat },
        Trip11: { type: GraphQLFloat },
        Hba_a2: { type: GraphQLFloat },
        Ptpn7: { type: GraphQLFloat },
        Oxsr1: { type: GraphQLFloat },
        _4930535C22Rik: { type: GraphQLFloat },
        Stk25: { type: GraphQLFloat },
        _4930471M09Rik: { type: GraphQLFloat },
        Dmc1: { type: GraphQLFloat },
        mt_Tf: { type: GraphQLFloat },
        Hrasls5: { type: GraphQLFloat },
        Gm6288: { type: GraphQLFloat },
        Gm25132: { type: GraphQLFloat },
        Zar1l: { type: GraphQLFloat },
        Abhd16a: { type: GraphQLFloat },
        Gm23218: { type: GraphQLFloat },
        Gm27042: { type: GraphQLFloat },
        Ighmbp2: { type: GraphQLFloat },
        Gm26070: { type: GraphQLFloat },
        Pcdhga8: { type: GraphQLFloat },
        Tspan9: { type: GraphQLFloat },
        Gm25617: { type: GraphQLFloat },
        Gm16333: { type: GraphQLFloat },
        Exph5: { type: GraphQLFloat },
        Tmem241: { type: GraphQLFloat },
        Fendrr: { type: GraphQLFloat },
        Zbtb8b: { type: GraphQLFloat },
        Pabpn1l: { type: GraphQLFloat },
        Gm25410: { type: GraphQLFloat },
        Gm24945: { type: GraphQLFloat },
        Glud1: { type: GraphQLFloat },
        Gm16163: { type: GraphQLFloat },
        Klhl23: { type: GraphQLFloat },
        AI646519: { type: GraphQLFloat },
        Scgb1a1: { type: GraphQLFloat },
        Ccr1l1: { type: GraphQLFloat },
        Loxl3: { type: GraphQLFloat },
        Mir142: { type: GraphQLFloat },
        Hes5: { type: GraphQLFloat },
        Zfp273: { type: GraphQLFloat },
        AC132444_1: { type: GraphQLFloat },
        St3gal6: { type: GraphQLFloat },
        Atp5g3: { type: GraphQLFloat },
        Kidins220: { type: GraphQLFloat },
        Dbx1: { type: GraphQLFloat },
        RP23_53N23_3: { type: GraphQLFloat },
        Ldb2: { type: GraphQLFloat },
        Rtn4rl2: { type: GraphQLFloat },
        Gm11608: { type: GraphQLFloat },
        Klk1b26: { type: GraphQLFloat },
        Gm23572: { type: GraphQLFloat },
        Drap1: { type: GraphQLFloat },
        Sfi1: { type: GraphQLFloat },
        Cep85l: { type: GraphQLFloat },
        Gm11961: { type: GraphQLFloat },
        Vav1: { type: GraphQLFloat },
        Fam214a: { type: GraphQLFloat },
        Rab42: { type: GraphQLFloat },
        Bloc1s1: { type: GraphQLFloat },
        Acox2: { type: GraphQLFloat },
        Cbll1: { type: GraphQLFloat },
        Ube2a: { type: GraphQLFloat },
        RP23_292B24_1: { type: GraphQLFloat },
        Gm37756: { type: GraphQLFloat },
        Ace3: { type: GraphQLFloat },
        Thyn1: { type: GraphQLFloat },
        Fgf20: { type: GraphQLFloat },
        Nat14: { type: GraphQLFloat },
        Sec61a2: { type: GraphQLFloat },
        Tmeff1: { type: GraphQLFloat },
        Zfyve27: { type: GraphQLFloat },
        Gm11650: { type: GraphQLFloat },
        Fgd6: { type: GraphQLFloat },
        Slc25a41: { type: GraphQLFloat },
        Gm12295: { type: GraphQLFloat },
        Lalba: { type: GraphQLFloat },
        Gm21989: { type: GraphQLFloat },
        Cenpi: { type: GraphQLFloat },
        Gm23967: { type: GraphQLFloat },
        Scn8a: { type: GraphQLFloat },
        Cdc37: { type: GraphQLFloat },
        Supt4a: { type: GraphQLFloat },
        Stxbp3: { type: GraphQLFloat },
        Arhgap27: { type: GraphQLFloat },
        _1700039M15Rik: { type: GraphQLFloat },
        Timm8b: { type: GraphQLFloat },
        Spon1: { type: GraphQLFloat },
        Zfp251: { type: GraphQLFloat },
        Zfp618: { type: GraphQLFloat },
      },
      resolve: (obj, args, ctx) => {
        return fetchExpressionDetails(ctx)
      },
    }
    */
  }),
})

const Schema = new GraphQLSchema({
  query: rootType,
  types: [MetadataType] 
  //types: datasetSpecificTypes,
})

export default Schema